<?xml version="1.0"?>
<sdf version="1.7" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- ===== Centralized parameters ===== -->
  <xacro:property name="box_x" value="1.0"/>     <!-- length (m) -->
  <xacro:property name="box_y" value="0.5"/>     <!-- width (m)  -->
  <xacro:property name="box_z" value="0.25"/>    <!-- height (m) -->
  <xacro:property name="mass"  value="2.0"/>     <!-- kg -->

  <!-- Derived values -->
  <xacro:property name="z_on_ground" value="${box_z/2.0}"/>
  <!-- Box inertia: Ixx = m*(y^2+z^2)/12, etc. -->
  <xacro:property name="ixx" value="${mass * (box_y**2 + box_z**2) / 12.0}"/>
  <xacro:property name="iyy" value="${mass * (box_x**2 + box_z**2) / 12.0}"/>
  <xacro:property name="izz" value="${mass * (box_x**2 + box_y**2) / 12.0}"/>

  <world name="default">
    <physics name="1ms" type="ignored">
      <max_step_size>0.001</max_step_size>
      <real_time_factor>1.0</real_time_factor>
    </physics>
    <plugin
      filename="ignition-gazebo-physics-system"
      name="gz::sim::systems::Physics">
    </plugin>
    <plugin
      filename="ignition-gazebo-user-commands-system"
      name="gz::sim::systems::UserCommands">
    </plugin>
    <plugin
      filename="ignition-gazebo-scene-broadcaster-system"
      name="gz::sim::systems::SceneBroadcaster">
    </plugin>
    <plugin
      filename="ignition-gazebo-contact-system"
      name="gz::sim::systems::Contact">
    </plugin>
    
    <light type="directional" name="sun">
      <cast_shadows>true</cast_shadows>
      <pose>0 0 10 0 0 0</pose>
      <diffuse>0.8 0.8 0.8 1</diffuse>
      <specular>0.2 0.2 0.2 1</specular>
      <attenuation>
        <range>1000</range>
        <constant>0.9</constant>
        <linear>0.01</linear>
        <quadratic>0.001</quadratic>
      </attenuation>
      <direction>-0.5 0.1 -0.9</direction>
    </light>
    
    <model name="ground_plane">
      <static>true</static>
      <link name="link">
        <collision name="collision">
          <geometry>
            <plane>
              <normal>0 0 1</normal>
              <size>100 100</size>
            </plane>
          </geometry>
        </collision>
        <visual name="visual">
          <geometry>
            <plane>
              <normal>0 0 1</normal>
              <size>100 100</size>
            </plane>
          </geometry>
          <material>
            <ambient>0.8 0.8 0.8 1</ambient>
            <diffuse>0.8 0.8 0.8 1</diffuse>
            <specular>0.8 0.8 0.8 1</specular>
          </material>
        </visual>
      </link>
    </model>


    <model name="my_cuboid">
      <pose>0 0 ${z_on_ground} 0 0 0</pose>
      <static>false</static>

      <link name="link">
        <inertial>
          <mass>${mass}</mass>
          <inertia>
            <ixx>${ixx}</ixx>
            <iyy>${iyy}</iyy>
            <izz>${izz}</izz>
            <ixy>0</ixy>
            <ixz>0</ixz>
            <iyz>0</iyz>
          </inertia>
        </inertial>

        <collision name="box_collision">
          <geometry>
            <box>
              <size>${box_x} ${box_y} ${box_z}</size>
            </box>
          </geometry>
          <surface>
            <friction>
              <ode>
                <mu>1.0</mu>
                <mu2>1.0</mu2>
              </ode>
            </friction>
            <contact><ode/></contact>
          </surface>
        </collision>

        <visual name="box_visual">
          <geometry>
            <box>
              <size>${box_x} ${box_y} ${box_z}</size>
            </box>
          </geometry>
          <material>
            <ambient>0.2 0.6 0.8 1</ambient>
            <diffuse>0.2 0.6 0.8 1</diffuse>
            <specular>0.1 0.1 0.1 1</specular>
          </material>
          <cast_shadows>true</cast_shadows>
        </visual>
      </link>
    </model>
  </world>
</sdf>
